<?php
$this->setPageID('pOverseasSgktph');
$this->setPageTitle('新加坡邱德拔医院');
?>
<div data-role="page" id="<?php echo $this->getPageID(); ?>" data-title="<?php echo $this->getPageTitle(); ?>" <?php echo $this->createPageAttributes(); ?>  back-btn-text="返回" data-nav-rel="#f-nav-hospital">
    <div data-role="content" class="ui-content" role="main">                
        <section>
            <div id="h-ktph" class="mt20 x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                <div id="h-elizabeth" class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                    <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border:0;margin: 0 0 0.5em 0" class="ng-scope"><section style="display: inline-block; padding: 0px 2px 2px; box-sizing: border-box; border-bottom-width: 2px; border-bottom-style: solid; border-color: rgb(142, 201, 101); line-height: 1; font-size: 1em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: center; text-decoration: inherit; color: white; background-color: transparent;" tn-page-editable="richtext0" tn-not-editable-attr="backgroundColor" tn-page-editable-type="ed-type-rich-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor),
                                                                                                                                                                                                        'background-color': (eo.backgroundColor || theme.majorColor),
                                                                                                                                                                                                        'border-color'    : (eo.borderColor || theme.majorColor)
                                                                                                                                                                                                        } " class="ng-scope tn-page-editable"><span style="display: inline-block; /* margin-left: 0.4em; */ max-width: 100%; color: rgb(0, 112, 192); line-height: 1.4;
                                                                          font-size: 1em; word-wrap: break-word !important"><strong style="max-width: 100%; word-wrap: break-word !important; font-size: 1em; font-family: inherit; font-style: normal; font-weight: bolder; text-align: inherit; text-decoration: inherit; color: rgb(142, 201, 101);" tn-page-editable="text1" tn-page-editable-type="ed-type-text" ng-style=" {
                                                      'font-size'       : eo.fontSize || 'inherit',
                                                      'font-family'     : eo.fontFamily || 'inherit',
                                                      'font-style'      : eo.fontStyle || 'inherit',
                                                      'font-weight'     : eo.fontWeight || 'inherit',
                                                      'text-align'      : eo.textAlign || 'inherit',
                                                      'text-decoration' : eo.textDecoration || 'inherit',
                                                      'color'           : (eo.color || theme.majorColor)
                                                      } " ng-bind-html="eo.text | eol2br | unsafe" class="ng-scope tn-page-editable ng-binding"><section>新加坡邱德拔医院</section></strong></span></section></fieldset></div></div>
                </div>
                <div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                    <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border: 0px; margin-top: 0px; margin-bottom: 0px; clear: both; font-size: 1em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: justify; text-decoration: inherit; color: inherit;" tn-page-editable="text0" class="ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor)
                                                                                                                                                                                                        } " ng-bind-html="eo.text | eol2br | unsafe"><section>邱德拔医院是最新的新一代在新加坡的急性护理综合性医院。拥有8个国家的最先进的手术室，四个内镜套房，两个重症监护暨高度依赖单位和康复健身房。</section></fieldset></div></div>
                </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                    <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border:0;box-sizing: border-box; width: 100%; margin: 0.8em 0 0.2em 0;clear: both" class="ng-scope"><img style="width:100%;" src="http://mingyihz.oss-cn-hangzhou.aliyuncs.com/static%2Foverseas_sg_ktph01.jpg"></fieldset></div></div>
                </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                    <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border:0;box-sizing: border-box; width: 100%; margin: 0.8em 0 0.2em 0;clear: both" class="ng-scope"><img style="width:100%;" src="http://mingyihz.oss-cn-hangzhou.aliyuncs.com/static%2Foverseas_sg_ktph02.jpg"></fieldset></div></div>
                </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                    <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border: 0px; margin-top: 0px; margin-bottom: 0px; clear: both; font-size: 1em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: justify; text-decoration: inherit; color: inherit;" tn-page-editable="text0" class="ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor)
                                                                                                                                                                                                        } " ng-bind-html="eo.text | eol2br | unsafe"><section>邱德拔医院，从外观看不像一家医院，更像一个公园，却为病人和居民提供了良好的就医环境和休闲场所，体现了新加坡以人为本的理念。医院宗旨为为病人提供全面而又便利的服务；只要能照顾到病人的需要，这将有助病人更快、更好地痊愈。</section></fieldset></div></div>
                </div><!-- end ngRepeat: slice in slices -->

                <div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                    <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border:0;box-sizing: border-box; width: 100%; margin: 0.8em 0 0.2em 0;clear: both" class="ng-scope"><img style="width:100%;" src="http://mingyihz.oss-cn-hangzhou.aliyuncs.com/static%2Foverseas_sg_ktph03.jpg"></fieldset></div></div>
                </div>

                <div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                    <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border:0;box-sizing: border-box; width: 100%; margin: 0.8em 0 0.2em 0;clear: both" class="ng-scope"><img style="width:100%;" src="http://mingyihz.oss-cn-hangzhou.aliyuncs.com/static%2Foverseas_sg_ktph04.jpg"></fieldset></div></div>
                </div><!-- end ngRepeat: slice in slices -->
                <div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                    <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border:0;margin: 1em; padding: 0" class="ng-scope"><section tn-page-editable="richtext0" tn-not-editable-attr="backgroundColor" tn-page-editable-type="ed-type-rich-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor),
                                                                                                                                                                                                        'background-color': (eo.backgroundColor || theme.majorColor),
                                                                                                                                                                                                        'border-color'    : (eo.borderColor || theme.majorColor)
                                                                                                                                                                                                        } " class="ng-scope tn-page-editable" style="font-size: 1em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: inherit; text-decoration: inherit; color: white; border-color: rgb(142, 201, 101); background-color: transparent;"><section style="display: inline-block; padding: 3px 8px; line-height: 1.4; border-top-left-radius: 8px; border-top-right-radius: 8px; font-family: inherit; font-style: normal; color: white; background-color: rgb(142, 201, 101);" ng-style="{ 'font-family': eo.fontFamily, 'font-style': eo.fontStyle, 'font-weight': eo.fontWeight,
                                                                                                                                                                                                        'text-align': eo.textAlign, 'text-decoration': eo.textDecoration, 'color': eo.color,
                                                                                                                                                                                                        'background-color': (eo.borderColor || theme.majorColor)}" ng-bind-html="eo.text | eol2br | unsafe" class="tn-rich-text-content ng-scope ng-binding"><section>邱德拔医院 重点科室</section></section><section style="margin-top: -1px; box-sizing: border-box; border: 1px solid rgb(142, 201, 101); border-bottom-left-radius: 8px; border-bottom-right-radius: 8px;" ng-style="{ 'border-color': (eo.borderColor || theme.majorColor) }"><section style="padding: 16px; border-bottom-left-radius: 8px; border-bottom-right-radius: 8px; line-height: 1.4; font-size: 1em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: inherit; text-decoration: inherit; color: rgb(51, 51, 51); border-color: rgb(249, 110, 87); background-color: transparent;" tn-page-editable="richtext1" tn-not-editable-attr="borderColor" ng-bind-html="eo.text | eol2br | unsafe" class="tn-rich-text-content ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-rich-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor),
                                                                                                                                                                                                        'background-color': (eo.backgroundColor || theme.majorColor),
                                                                                                                                                                                                        'border-color'    : (eo.borderColor || theme.majorColor)
                                                                                                                                                                                                        } "><section>妇产科</section><section>肿瘤</section><section>牙齿和口腔外科<br>整形外科</section><section>糖尿病护理</section><section>免疫学和风湿病</section></section></section></section></fieldset></div></div>
                </div><!-- end ngRepeat: slice in slices -->				
            </div></section>
    </div>
</div>