<?php
$this->setPageID('pOverseasSgktph');
$this->setPageTitle('新加坡国立大学医院');
?>
<div data-role="page" id="<?php echo $this->getPageID(); ?>" data-title="<?php echo $this->getPageTitle(); ?>" <?php echo $this->createPageAttributes(); ?>  back-btn-text="返回" data-nav-rel="#f-nav-hospital">
    <div data-role="content" class="ui-content" role="main">
        <section>
            <div id="h-nuh" class="mt20 x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                <div id="h-elizabeth" class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                    <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border:0;margin: 0 0 0.5em 0" class="ng-scope"><section style="display: inline-block; padding: 0px 2px 2px; box-sizing: border-box; border-bottom-width: 2px; border-bottom-style: solid; border-color: rgb(142, 201, 101); line-height: 1; font-size: 1em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: center; text-decoration: inherit; color: white; background-color: transparent;" tn-page-editable="richtext0" tn-not-editable-attr="backgroundColor" tn-page-editable-type="ed-type-rich-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor),
                                                                                                                                                                                                        'background-color': (eo.backgroundColor || theme.majorColor),
                                                                                                                                                                                                        'border-color'    : (eo.borderColor || theme.majorColor)
                                                                                                                                                                                                        } " class="ng-scope tn-page-editable"><span style="display: inline-block; /* margin-left: 0.4em; */ max-width: 100%; color: rgb(0, 112, 192); line-height: 1.4;
                                                                          font-size: 1em; word-wrap: break-word !important"><strong style="max-width: 100%; word-wrap: break-word !important; font-size: 1em; font-family: inherit; font-style: normal; font-weight: bolder; text-align: inherit; text-decoration: inherit; color: rgb(142, 201, 101);" tn-page-editable="text1" tn-page-editable-type="ed-type-text" ng-style=" {
                                                      'font-size'       : eo.fontSize || 'inherit',
                                                      'font-family'     : eo.fontFamily || 'inherit',
                                                      'font-style'      : eo.fontStyle || 'inherit',
                                                      'font-weight'     : eo.fontWeight || 'inherit',
                                                      'text-align'      : eo.textAlign || 'inherit',
                                                      'text-decoration' : eo.textDecoration || 'inherit',
                                                      'color'           : (eo.color || theme.majorColor)
                                                      } " ng-bind-html="eo.text | eol2br | unsafe" class="ng-scope tn-page-editable ng-binding"><section>新加坡国立大学医院</section></strong></span></section></fieldset></div></div>
                </div>
                <div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                    <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border: 0px; margin-top: 0px; margin-bottom: 0px; clear: both; font-size: 1em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: justify; text-decoration: inherit; color: inherit;" tn-page-editable="text0" class="ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor)
                                                                                                                                                                                                        } " ng-bind-html="eo.text | eol2br | unsafe"><section>新加坡国立大学医院提供全面医疗服务的医院，主要强项包括心脏科、妇产科、肿瘤科、儿科、眼科、骨科以及肠胃科。作为新加坡唯一一家教学医院，国大医院里头大多医生也在新加坡国立大学属下的杨潞龄医学院执教。这种行医兼执教的安排，可确保医生们清楚掌握医学技术和科技的最新发展，让他们通过参与研究的方式，把最新的疗程从实验室带到医院给病人。</section></fieldset></div></div>
                </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                    <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border:0;box-sizing: border-box; width: 100%; margin: 0.8em 0 0.2em 0;clear: both" class="ng-scope"><img style="width:100%;" src="http://mingyihz.oss-cn-hangzhou.aliyuncs.com/static%2Foverseas_sg_nuh01.jpg"></fieldset></div></div>
                </div><!-- end ngRepeat: slice in slices -->
                <div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                    <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border: 0px; margin-top: 0px; margin-bottom: 0px; clear: both; font-size: 1em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: justify; text-decoration: inherit; color: inherit;" tn-page-editable="text0" class="ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor)
                                                                                                                                                                                                        } " ng-bind-html="eo.text | eol2br | unsafe"><section>国大医院是第一家医院在亚太区提供非药物治疗哮喘支气管的医院；成功进行了新加坡第一次双重器官移植（肝，肾）和胰肾联合移植手术。<br></section></fieldset></div></div>
                </div><!-- end ngRepeat: slice in slices --><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                    <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border:0;box-sizing: border-box; width: 100%; margin: 0.8em 0 0.2em 0;clear: both" class="ng-scope"><img style="width:100%;" src="http://mingyihz.oss-cn-hangzhou.aliyuncs.com/static%2Foverseas_sg_nuh02.jpg"></fieldset></div></div>
                </div><!-- end ngRepeat: slice in slices --><div class="pb20 x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                    <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border:0;margin: 1em; padding: 0" class="ng-scope"><section tn-page-editable="richtext0" tn-not-editable-attr="backgroundColor" tn-page-editable-type="ed-type-rich-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor),
                                                                                                                                                                                                        'background-color': (eo.backgroundColor || theme.majorColor),
                                                                                                                                                                                                        'border-color'    : (eo.borderColor || theme.majorColor)
                                                                                                                                                                                                        } " class="ng-scope tn-page-editable" style="font-size: 1em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: inherit; text-decoration: inherit; color: white; border-color: rgb(142, 201, 101); background-color: transparent;"><section style="display: inline-block; padding: 3px 8px; line-height: 1.4; border-top-left-radius: 8px; border-top-right-radius: 8px; font-family: inherit; font-style: normal; color: white; background-color: rgb(142, 201, 101);" ng-style="{ 'font-family': eo.fontFamily, 'font-style': eo.fontStyle, 'font-weight': eo.fontWeight,
                                                                                                                                                                                                        'text-align': eo.textAlign, 'text-decoration': eo.textDecoration, 'color': eo.color,
                                                                                                                                                                                                        'background-color': (eo.borderColor || theme.majorColor)}" ng-bind-html="eo.text | eol2br | unsafe" class="tn-rich-text-content ng-scope ng-binding"><section>国立大学医院 &nbsp;重点科室</section></section><section style="margin-top: -1px; box-sizing: border-box; border: 1px solid rgb(142, 201, 101); border-bottom-left-radius: 8px; border-bottom-right-radius: 8px;" ng-style="{ 'border-color': (eo.borderColor || theme.majorColor) }"><section style="padding: 16px; border-bottom-left-radius: 8px; border-bottom-right-radius: 8px; line-height: 1.4; font-size: 1em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: inherit; text-decoration: inherit; color: rgb(51, 51, 51); border-color: rgb(249, 110, 87); background-color: transparent;" tn-page-editable="richtext1" tn-not-editable-attr="borderColor" ng-bind-html="eo.text | eol2br | unsafe" class="tn-rich-text-content ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-rich-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor),
                                                                                                                                                                                                        'background-color': (eo.backgroundColor || theme.majorColor),
                                                                                                                                                                                                        'border-color'    : (eo.borderColor || theme.majorColor)
                                                                                                                                                                                                        } "><section>牙科<br>肿瘤</section><section>骨科</section><section>心脏科</section><section>肠胃科</section></section></section></section></fieldset></div></div>
                </div>
            </div></section>

    </div>
</div>